#!/bin/bash

OPENSHIFT_DOMAIN_RHSADEMO=rhsademo.net

OPENSHIFT_DOMAIN=${OPENSHIFT_DOMAIN_RHSADEMO}

OPENSHIFT_MASTER_RHSADEMO=master.${OPENSHIFT_DOMAIN_RHSADEMO}
OPENSHIFT_PRIMARY_MASTER_PORT_HTTPS=443

OPENSHIFT_PRIMARY_PROXY_AUTH=proxy.${OPENSHIFT_MASTER_RHSADEMO}

OPENSHIFT_PRIMARY_APPS=apps.${OPENSHIFT_DOMAIN_RHSADEMO}

OPENSHIFT_PRIMARY_AUTH_METHOD=token

OPENSHIFT_USER_PRIMARY_DEFAULT=mepley
OPENSHIFT_USER_PRIMARY=${OPENSHIFT_USER_PRIMARY_DEFAULT}
OPENSHIFT_USER_PRIMARY_PASSWORD=${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT}

OPENSHIFT_PRIMARY_CEREDENTIALS_CLI_DEFAULT=
OPENSHIFT_PRIMARY_PROJECT_AMQ_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-fuse-amq
OPENSHIFT_PRIMARY_PROJECT_MYSQLPHP_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-myphp
OPENSHIFT_PRIMARY_PROJECT_DEFAULT=${OPENSHIFT_PRIMARY_PROJECT_MYSQLPHP_DEFAULT}
OPENSHIFT_PRIMARY_PROJECT=${OPENSHIFT_PRIMARY_PROJECT_DEFAULT}

if [[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT ]] ; then
	echo "--> Using RHSADEMO password for openshift"
	OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=$OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT
else
	[[ ! -v OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT ]] && echo "Please set OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT to your openshift password" && exit 1
fi

echo "	--> FYI: ssh access to rhsademo available vi jump.rhsademo.net" && echo "	--> Use: ssh -vvv -i ~/.ssh/id_rsa_openshift mepley@jump.rhsademo.net"
