#!/bin/bash

. config-resources-available-all.sh || { echo "FAILED: Could not load available resource index" && exit 1; }

[[ -v CONFIGURATION_DEMO_TARGET_RHSADEMO_COMPLETED ]] && echo "Using demo target RHSADEMO configuration" && { return || exit ; }
: ${CONFIGURATION_DEMO_TARGET_RHSADEMO_DISPLAY:=$CONFIGURATION_DISPLAY}

# variables marked as "PRIMARY", "SECONDARY", etc denote available alternatives 
OPENSHIFT_DOMAIN_RHSADEMO_PRIMARY=rhsademo.net
OPENSHIFT_DOMAIN_PRIMARY=${OPENSHIFT_DOMAIN_RHSADEMO_PRIMARY}
OPENSHIFT_DOMAIN_RHSADEMO=${OPENSHIFT_DOMAIN_RHSADEMO_PRIMARY}
OPENSHIFT_MASTER_RHSADEMO_PRIMARY=master.${OPENSHIFT_DOMAIN_RHSADEMO}
OPENSHIFT_MASTER_RHSADEMO_PRIMARY_PORT_HTTPS=443
OPENSHIFT_APPS_RHSADEMO_PRIMARY=apps.${OPENSHIFT_DOMAIN_RHSADEMO}
OPENSHIFT_PROXY_AUTH_RHSADEMO_PRIMARY=proxy.${OPENSHIFT_DOMAIN_RHSADEMO}
OPENSHIFT_AUTH_METHOD_RHSADEMO_PRIMARY=token

OPENSHIFT_APPLICATION_NAME_MYPHP=myphp

OPENSHIFT_PRIMARY_CREDENTIALS_CLI_DEFAULT=

# get encryption/decryption key if one is not provided automatically
[[ -v SCRIPT_ENCRYPTION_KEY ]] || { read -t 10 -s -p "======> ENTER ENCRYPTION/DECRYPTION KEY:" SCRIPT_ENCRYPTION_KEY && echo "" ; }
# assume a default key if the user did not supply one in time
: ${SCRIPT_ENCRYPTION_KEY:=$OPENSHIFT_USER_PRIMARY_PASSWORD}

[[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT ]] || [[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_CIPHERTEXT ]] || { echo "FAILED: OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT must be set and match a valid GitHub.com Oauth2 personal access token with the following roles:" ; }
#OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT=`echo ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_CIPHERTEXT} | openssl enc -d -a | openssl enc -d -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY} `
[[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT ]] && ! [[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_CIPHERTEXT ]] && echo "--> it is recommended to use an encrypted token; you may encrypt and store the token using the following: " && echo ' OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_CIPHERTEXT=`echo ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT} | openssl enc -e -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY} | openssl enc -e -a`'
[[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_CIPHERTEXT ]] && OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT=`echo ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_CIPHERTEXT} | openssl enc -d -a | openssl enc -d -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY}` || { echo "FAILED: Could not validate the password" && exit 1; }

# each user entry is an array of (username, password, auth-method default project, and any other projects)
OPENSHIFT_USER_RHSADEMO_MEPLEY=(mepley ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT} token mepley-default)
OPENSHIFT_USER_RHSADEMO_MEPLEY2=(mepley2 ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT} token mepley2-default)
OPENSHIFT_USER_RHSADEMO_MEPLEY_DEV=(mepley ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT} token mepley-development)
OPENSHIFT_USER_RHSADEMO_MEPLEY_TEST=(mepley ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT} token mepley-testing)
OPENSHIFT_USER_RHSADEMO_MEPLEY_PROD=(mepley ${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT_PLAINTEXT} token mepley-production)
# array of all users for this demo target
OPENSHIFT_USERS_RHSADEMO=(OPENSHIFT_USER_RHSADEMO_MEPLEY OPENSHIFT_USER_RHSADEMO_MEPLEY2 OPENSHIFT_USER_RHSADEMO_MEPLEY_DEV OPENSHIFT_USER_RHSADEMO_MEPLEY_TEST OPENSHIFT_USER_RHSADEMO_MEPLEY_PROD)

if [ "$CONFIGURATION_DEMO_TARGET_RHSADEMO_DISPLAY" != "false" ]; then
	echo "Demo Target RHSADEMO Configuration__________________________"
	echo "	OPENSHIFT_DOMAIN_RHSADEMO_PRIMARY           = ${OPENSHIFT_DOMAIN_RHSADEMO_PRIMARY}"
	echo "	OPENSHIFT_DOMAIN_PRIMARY                    = ${OPENSHIFT_DOMAIN_PRIMARY}"
	echo "	OPENSHIFT_DOMAIN_RHSADEMO                   = ${OPENSHIFT_DOMAIN_RHSADEMO}"
	echo "	OPENSHIFT_MASTER_RHSADEMO_PRIMARY           = ${OPENSHIFT_MASTER_RHSADEMO_PRIMARY}"
	echo "	OPENSHIFT_MASTER_RHSADEMO_PRIMARY_PORT_HTTPS= ${OPENSHIFT_MASTER_RHSADEMO_PRIMARY_PORT_HTTPS}"
	echo "	OPENSHIFT_APPS_RHSADEMO_PRIMARY             = ${OPENSHIFT_APPS_RHSADEMO_PRIMARY}"
	echo "	OPENSHIFT_PROXY_AUTH_RHSADEMO_PRIMARY       = ${OPENSHIFT_PROXY_AUTH_RHSADEMO_PRIMARY}"
	echo "	OPENSHIFT_AUTH_METHOD_RHSADEMO_PRIMARY      = ${OPENSHIFT_AUTH_METHOD_RHSADEMO_PRIMARY}"
	echo "	OPENSHIFT_USERS_RHSADEMO = {"
	for OPENSHIFT_USER_RHSADEMO in ${!OPENSHIFT_USERS_RHSADEMO[@]}; do
		echo " OPENSHIFT_USER_RHSADEMO is ${OPENSHIFT_USER_RHSADEMO}"
		echo -n "		${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]} : "
		OPENSHIFT_USER_RHSADEMO_USERNAME_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[0] && echo -n "( username = ${!OPENSHIFT_USER_RHSADEMO_USERNAME_REF} , "
		OPENSHIFT_USER_RHSADEMO_PASSWORD_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[1] && echo -n "password (obfuscated) = ` echo ${!OPENSHIFT_USER_RHSADEMO_PASSWORD_REF} | md5sum`, "
		OPENSHIFT_USER_RHSADEMO_AUTHMETHOD_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[2] && echo -n "auth-method = ${!OPENSHIFT_USER_RHSADEMO_AUTHMETHOD_REF} , "
		OPENSHIFT_USER_RHSADEMO_PROJECT_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[3] && echo -n "project = ${!OPENSHIFT_USER_RHSADEMO_PROJECT_REF} )"
		echo ""
	done
	echo "	}"
	echo "____________________________________________________________"
	echo "	--> FYI: ssh access to rhsademo available vi jump.rhsademo.net" && echo "	--> Use: ssh -vvv -i ~/.ssh/id_rsa_openshift mepley@jump.rhsademo.net"
fi

# overwrite  generic configuration with RHSAMEMO specific configuration
OPENSHIFT_DOMAIN_DEFAULT=${OPENSHIFT_DOMAIN_RHSADEMO_PRIMARY}
OPENSHIFT_MASTER_PRIMARY_DEFAULT=${OPENSHIFT_MASTER_RHSADEMO_PRIMARY}
OPENSHIFT_MASTER_PRIMARY_DEFAULT_PORT_HTTPS=${OPENSHIFT_MASTER_RHSADEMO_PRIMARY_PORT_HTTPS}
OPENSHIFT_APPS_PRIMARY_DEFAULT=${OPENSHIFT_APPS_RHSADEMO_PRIMARY}
OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT=${OPENSHIFT_PROXY_AUTH_RHSADEMO_PRIMARY}
OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT="OPENSHIFT_USER_RHSADEMO_MEPLEY"
OPENSHIFT_USER_PRIMARY_DEFAULT=${OPENSHIFT_USER_RHSADEMO_MEPLEY[0]}
OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=${OPENSHIFT_USER_RHSADEMO_MEPLEY[1]}
OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT=${OPENSHIFT_USER_RHSADEMO_MEPLEY[2]}
OPENSHIFT_PROJECT_PRIMARY_DEFAULT=${OPENSHIFT_USER_RHSADEMO_MEPLEY[3]}
: ${OPENSHIFT_APPLICATION_NAME_DEFAULT:=default-app}
: ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT:=json}

CONFIGURATION_DEMO_TARGET_RHSADEMO_COMPLETED=true
