#!/bin/bash

. config-resources-available-all.sh || { echo "FAILED: Could not load available resource index" && exit 1; }

[[ -v CONFIGURATION_DEMO_TARGET_RHSADEMO_COMPLETED ]] && echo "Using demo target FORTNEBULA configuration" && { return || exit ; }
: ${CONFIGURATION_DEMO_TARGET_RHSADEMO_DISPLAY:=$CONFIGURATION_DISPLAY}

# variables marked as "PRIMARY", "SECONDARY", etc denote available alternatives 
OPENSHIFT_DOMAIN_FORTNEBULA_PRIMARY=openshift.fortnebula.com
OPENSHIFT_DOMAIN_PRIMARY=${OPENSHIFT_DOMAIN_FORTNEBULA_PRIMARY}
OPENSHIFT_DOMAIN_FORTNEBULA=${OPENSHIFT_DOMAIN_FORTNEBULA_PRIMARY}
OPENSHIFT_MASTER_FORTNEBULA_PRIMARY=master.${OPENSHIFT_DOMAIN_FORTNEBULA}
OPENSHIFT_MASTER_FORTNEBULA_PRIMARY_PORT_HTTPS=8443
OPENSHIFT_APPS_FORTNEBULA_PRIMARY=apps.${OPENSHIFT_DOMAIN_FORTNEBULA}
OPENSHIFT_PROXY_AUTH_FORTNEBULA_PRIMARY=proxy.${OPENSHIFT_DOMAIN_FORTNEBULA}
OPENSHIFT_AUTH_METHOD_FORTNEBULA_PRIMARY=token

OPENSHIFT_APPLICATION_NAME_MYPHP=myphp

OPENSHIFT_PRIMARY_CREDENTIALS_CLI_DEFAULT=

# TODO: store default password as ciphertext, as is done with github auth token 
## OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_CIPHERTEXT
## OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT
if [[ -v OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT ]] ; then
	echo "--> Using FORTNEBULA password for openshift"
	OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=$OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT
else
	[[ ! -v OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT ]] && echo "Please set OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT to your openshift password" && exit 1
fi

# get encryption/decryption key if one is not provided automatically
[[ -v SCRIPT_ENCRYPTION_KEY ]] || { read -t 10 -s -p "======> ENTER ENCRYPTION/DECRYPTION KEY:" SCRIPT_ENCRYPTION_KEY && echo "" ; }
# assume a default key if the user did not supply one in time
: ${SCRIPT_ENCRYPTION_KEY:=$OPENSHIFT_USER_PRIMARY_PASSWORD}

[[ -v OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT ]] || [[ -v OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_CIPHERTEXT ]] || { echo "FAILED: OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT must be set and match a valid GitHub.com Oauth2 personal access token with the following roles:" ; }
#OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT=`echo ${OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_CIPHERTEXT} | openssl enc -d -a | openssl enc -d -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY} `
[[ -v OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT ]] && echo "--> it is recommended to use an encrypted token; you may encrypt and store the token using the following: " && echo ' OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_CIPHERTEXT=`echo ${OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT} | openssl enc -e -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY} | openssl enc -e -a`'
: ${OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_PLAINTEXT:-`echo ${OPENSHIFT_FORTNEBULA_USER_PASSWORD_DEFAULT_CIPHERTEXT} | openssl enc -d -a | openssl enc -d -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY}`} || { echo "FAILED: Could not validate the github token" && exit 1; }




# each user entry is an array of (username, password, auth-method default project, and any other projects)
OPENSHIFT_USER_FORTNEBULA_MEPLEY=(mike.epley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} token mepley-default)
OPENSHIFT_USER_FORTNEBULA_MEPLEY_DEV=(mike.epley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} token mepley-development)
OPENSHIFT_USER_FORTNEBULA_MEPLEY_TEST=(mike.epley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} token mepley-testing)
OPENSHIFT_USER_FORTNEBULA_MEPLEY_PROD=(mike.epley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} token mepley-production)
# array of all users for this demo target
OPENSHIFT_USERS_FORTNEBULA=(OPENSHIFT_USER_FORTNEBULA_MEPLEY OPENSHIFT_USER_FORTNEBULA_MEPLEY_DEV OPENSHIFT_USER_FORTNEBULA_MEPLEY_TEST OPENSHIFT_USER_FORTNEBULA_MEPLEY_PROD)

if [ "$CONFIGURATION_DEMO_TARGET_FORTNEBULA_DISPLAY" != "false" ]; then
	echo "Demo Target FORTNEBULA Configuration__________________________"
	echo "	OPENSHIFT_DOMAIN_FORTNEBULA_PRIMARY           = ${OPENSHIFT_DOMAIN_FORTNEBULA_PRIMARY}"
	echo "	OPENSHIFT_DOMAIN_PRIMARY                    = ${OPENSHIFT_DOMAIN_PRIMARY}"
	echo "	OPENSHIFT_DOMAIN_FORTNEBULA                   = ${OPENSHIFT_DOMAIN_FORTNEBULA}"
	echo "	OPENSHIFT_MASTER_FORTNEBULA_PRIMARY           = ${OPENSHIFT_MASTER_FORTNEBULA_PRIMARY}"
	echo "	OPENSHIFT_MASTER_FORTNEBULA_PRIMARY_PORT_HTTPS= ${OPENSHIFT_MASTER_FORTNEBULA_PRIMARY_PORT_HTTPS}"
	echo "	OPENSHIFT_APPS_FORTNEBULA_PRIMARY             = ${OPENSHIFT_APPS_FORTNEBULA_PRIMARY}"
	echo "	OPENSHIFT_PROXY_AUTH_FORTNEBULA_PRIMARY       = ${OPENSHIFT_PROXY_AUTH_FORTNEBULA_PRIMARY}"
	echo "	OPENSHIFT_AUTH_METHOD_FORTNEBULA_PRIMARY      = ${OPENSHIFT_AUTH_METHOD_FORTNEBULA_PRIMARY}"
	echo "	OPENSHIFT_USERS_FORTNEBULA = {"
	for OPENSHIFT_USER_FORTNEBULA in ${!OPENSHIFT_USERS_FORTNEBULA[@]}; do
		echo " OPENSHIFT_USER_FORTNEBULA is ${OPENSHIFT_USER_FORTNEBULA}"
		echo -n "		${OPENSHIFT_USERS_FORTNEBULA[$OPENSHIFT_USER_FORTNEBULA]} : "
		OPENSHIFT_USER_FORTNEBULA_USERNAME_REF=${OPENSHIFT_USERS_FORTNEBULA[$OPENSHIFT_USER_FORTNEBULA]}[0] && echo -n "( username = ${!OPENSHIFT_USER_FORTNEBULA_USERNAME_REF} , "
		OPENSHIFT_USER_FORTNEBULA_PASSWORD_REF=${OPENSHIFT_USERS_FORTNEBULA[$OPENSHIFT_USER_FORTNEBULA]}[1] && echo -n "password (obfuscated) = ` echo ${!OPENSHIFT_USER_FORTNEBULA_PASSWORD_REF} | md5sum`, "
		OPENSHIFT_USER_FORTNEBULA_AUTHMETHOD_REF=${OPENSHIFT_USERS_FORTNEBULA[$OPENSHIFT_USER_FORTNEBULA]}[2] && echo -n "auth-method = ${!OPENSHIFT_USER_FORTNEBULA_AUTHMETHOD_REF} , "
		OPENSHIFT_USER_FORTNEBULA_PROJECT_REF=${OPENSHIFT_USERS_FORTNEBULA[$OPENSHIFT_USER_FORTNEBULA]}[3] && echo -n "project = ${!OPENSHIFT_USER_FORTNEBULA_PROJECT_REF} )"
		echo ""
	done
	echo "	}"
	echo "____________________________________________________________"
	echo "	--> FYI: ssh access to rhsademo available vi jump.rhsademo.net" && echo "	--> Use: ssh -vvv -i ~/.ssh/id_rsa_openshift mepley@jump.rhsademo.net"
fi

# overwrite  generic configuration with RHSAMEMO specific configuration
OPENSHIFT_DOMAIN_DEFAULT=${OPENSHIFT_DOMAIN_FORTNEBULA_PRIMARY}
OPENSHIFT_MASTER_PRIMARY_DEFAULT=${OPENSHIFT_MASTER_FORTNEBULA_PRIMARY}
OPENSHIFT_MASTER_PRIMARY_DEFAULT_PORT_HTTPS=${OPENSHIFT_MASTER_FORTNEBULA_PRIMARY_PORT_HTTPS}
OPENSHIFT_APPS_PRIMARY_DEFAULT=${OPENSHIFT_APPS_FORTNEBULA_PRIMARY}
OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT=${OPENSHIFT_PROXY_AUTH_FORTNEBULA_PRIMARY}
OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT="OPENSHIFT_USER_FORTNEBULA_MEPLEY"
OPENSHIFT_USER_PRIMARY_DEFAULT=${OPENSHIFT_USER_FORTNEBULA_MEPLEY[0]}
OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=${OPENSHIFT_USER_FORTNEBULA_MEPLEY[1]}
OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT=${OPENSHIFT_USER_FORTNEBULA_MEPLEY[2]}
OPENSHIFT_PROJECT_PRIMARY_DEFAULT=${OPENSHIFT_USER_FORTNEBULA_MEPLEY[3]}
: ${OPENSHIFT_APPLICATION_NAME_DEFAULT:=default-app}
: ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT:=json}

CONFIGURATION_DEMO_TARGET_FORTNEBULA_COMPLETED=true
