#!/bin/bash

[[ -v CONFIGURATION_DEFAULT_COMPLETED ]] && echo "Using default configuration" && { return || exit ; }

# set to "false" to disable the echoing of configuration information
CONFIGURATION_DISPLAY=false

OPENSHIFT_DOMAIN_DEFAULT=rhsademo.net
OPENSHIFT_MASTER_PRIMARY_DEFAULT=master.${OPENSHIFT_DOMAIN_DEFAULT}
OPENSHIFT_APPS_PRIMARY_DEFAULT=apps.${OPENSHIFT_DOMAIN_DEFAULT}
OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT=proxy.${OPENSHIFT_DOMAIN_DEFAULT}
OPENSHIFT_USER_PRIMARY_DEFAULT=${USER}
OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT='password1!'
OPENSHIFT_PROJECT_PRIMARY_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-default
OPENSHIFT_APPLICATION_NAME_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-app
OPENSHIFT_OUTPUT_FORMAT_DEFAULT=json

if [ "$CONFIGURATION_DISPLAY" != "false" ]; then
	echo "Default Configuration_______________________________________"
	echo "	OPENSHIFT_DOMAIN_DEFAULT                = ${OPENSHIFT_DOMAIN_DEFAULT}"
	echo "	OPENSHIFT_MASTER_PRIMARY_DEFAULT        = ${OPENSHIFT_MASTER_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_APPS_PRIMARY_DEFAULT          = ${OPENSHIFT_APPS_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT    = ${OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_USER_PRIMARY_DEFAULT          = ${OPENSHIFT_USER_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT = `echo ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} | md5sum` (obfuscated)"
	echo "	OPENSHIFT_PROJECT_PRIMARY_DEFAULT       = ${OPENSHIFT_PROJECT_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_APPLICATION_NAME_DEFAULT      = ${OPENSHIFT_APPLICATION_NAME_DEFAULT}"
	echo "	OPENSHIFT_OUTPUT_FORMAT_DEFAULT         = ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT}"
	echo "____________________________________________________________"
fi

CONFIGURATION_DEFAULT_COMPLETED=true