#!/bin/bash

# See https://mojo.redhat.com/docs/DOC-1099943
# See https://open.paas.redhat.com/console/

. config-resources-available-all.sh || { echo "FAILED: Could not load available resource index" && exit 1; }

[[ -v CONFIGURATION_DEMO_TARGET_ITPAAS_COMPLETED ]] && echo "Using demo target ITPAAS configuration" && { return || exit ; }
: ${CONFIGURATION_DEMO_TARGET_ITPAAS_DISPLAY:=$CONFIGURATION_DISPLAY}

# variables marked as "PRIMARY", "SECONDARY", etc denote available alternatives 
OPENSHIFT_DOMAIN_ITPAAS_PRIMARY=open.paas.redhat.com
OPENSHIFT_DOMAIN_PRIMARY=${OPENSHIFT_DOMAIN_ITPAAS_PRIMARY}
OPENSHIFT_DOMAIN_ITPAAS=${OPENSHIFT_DOMAIN_ITPAAS_PRIMARY}
OPENSHIFT_MASTER_ITPAAS_PRIMARY=${OPENSHIFT_DOMAIN_ITPAAS}
OPENSHIFT_MASTER_ITPAAS_PRIMARY_PORT_HTTPS=443
OPENSHIFT_APPS_ITPAAS_PRIMARY=int.${OPENSHIFT_DOMAIN_ITPAAS}
OPENSHIFT_PROXY_AUTH_ITPAAS_PRIMARY=proxy.${OPENSHIFT_DOMAIN_ITPAAS}
OPENSHIFT_AUTH_METHOD_ITPAAS_PRIMARY=password

OPENSHIFT_APPLICATION_NAME_MYPHP=myphp

OPENSHIFT_PRIMARY_CREDENTIALS_CLI_DEFAULT=

# TODO: store default password as ciphertext, as is done with github auth token 
## OPENSHIFT_ITPAAS_USER_PASSWORD_DEFAULT_CIPHERTEXT
if [[ -v OPENSHIFT_ITPAAS_USER_PASSWORD_DEFAULT ]] ; then
	echo "--> Using ITPAAS password for openshift"
	OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=$OPENSHIFT_ITPAAS_USER_PASSWORD_DEFAULT
else
	[[ ! -v OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT ]] && echo "Please set OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT to your openshift password" && exit 1
fi


# each user entry is an array of (username, password, auth-method default project, and any other projects)
OPENSHIFT_USER_ITPAAS_MEPLEY=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} password mepley-default)
OPENSHIFT_USER_ITPAAS_MEPLEY_DEV=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} password mepley-development)
OPENSHIFT_USER_ITPAAS_MEPLEY_TEST=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} password mepley-testing)
OPENSHIFT_USER_ITPAAS_MEPLEY_PROD=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} password mepley-production)
# array of all users for this demo target
OPENSHIFT_USERS_ITPAAS=(OPENSHIFT_USER_ITPAAS_MEPLEY OPENSHIFT_USER_ITPAAS_MEPLEY2 OPENSHIFT_USER_ITPAAS_MEPLEY_DEV OPENSHIFT_USER_ITPAAS_MEPLEY_TEST OPENSHIFT_USER_ITPAAS_MEPLEY_PROD)


if [ "$CONFIGURATION_DEMO_TARGET_ITPAAS_DISPLAY" != "false" ]; then
	echo "Demo Target ITPAAS Configuration__________________________"
	echo "	OPENSHIFT_DOMAIN_ITPAAS_PRIMARY           = ${OPENSHIFT_DOMAIN_ITPAAS_PRIMARY}"
	echo "	OPENSHIFT_DOMAIN_PRIMARY                    = ${OPENSHIFT_DOMAIN_PRIMARY}"
	echo "	OPENSHIFT_DOMAIN_ITPAAS                   = ${OPENSHIFT_DOMAIN_ITPAAS}"
	echo "	OPENSHIFT_MASTER_ITPAAS_PRIMARY           = ${OPENSHIFT_MASTER_ITPAAS_PRIMARY}"
	echo "	OPENSHIFT_MASTER_ITPAAS_PRIMARY_PORT_HTTPS= ${OPENSHIFT_MASTER_ITPAAS_PRIMARY_PORT_HTTPS}"
	echo "	OPENSHIFT_APPS_ITPAAS_PRIMARY             = ${OPENSHIFT_APPS_ITPAAS_PRIMARY}"
	echo "	OPENSHIFT_PROXY_AUTH_ITPAAS_PRIMARY       = ${OPENSHIFT_PROXY_AUTH_ITPAAS_PRIMARY}"
	echo "	OPENSHIFT_AUTH_METHOD_ITPAAS_PRIMARY      = ${OPENSHIFT_AUTH_METHOD_ITPAAS_PRIMARY}"
	echo "	OPENSHIFT_USERS_ITPAAS = {"
	for OPENSHIFT_USER_ITPAAS in ${!OPENSHIFT_USERS_ITPAAS[@]}; do
		echo " OPENSHIFT_USER_ITPAAS is ${OPENSHIFT_USER_ITPAAS}"
		echo -n "		${OPENSHIFT_USERS_ITPAAS[$OPENSHIFT_USER_ITPAAS]} : "
		OPENSHIFT_USER_ITPAAS_USERNAME_REF=${OPENSHIFT_USERS_ITPAAS[$OPENSHIFT_USER_ITPAAS]}[0] && echo -n "( username = ${!OPENSHIFT_USER_ITPAAS_USERNAME_REF} , "
		OPENSHIFT_USER_ITPAAS_PASSWORD_REF=${OPENSHIFT_USERS_ITPAAS[$OPENSHIFT_USER_ITPAAS]}[1] && echo -n "password (obfuscated) = ` echo ${!OPENSHIFT_USER_ITPAAS_PASSWORD_REF} | md5sum`, "
		OPENSHIFT_USER_ITPAAS_AUTHMETHOD_REF=${OPENSHIFT_USERS_ITPAAS[$OPENSHIFT_USER_ITPAAS]}[2] && echo -n "auth-method = ${!OPENSHIFT_USER_ITPAAS_AUTHMETHOD_REF} , "
		OPENSHIFT_USER_ITPAAS_PROJECT_REF=${OPENSHIFT_USERS_ITPAAS[$OPENSHIFT_USER_ITPAAS]}[3] && echo -n "project = ${!OPENSHIFT_USER_ITPAAS_PROJECT_REF} )"
		echo ""
	done
	echo "	}"
	echo "____________________________________________________________"
fi

# overwrite  generic configuration with RHSAMEMO specific configuration
OPENSHIFT_DOMAIN_DEFAULT=${OPENSHIFT_DOMAIN_ITPAAS_PRIMARY}
OPENSHIFT_MASTER_PRIMARY_DEFAULT=${OPENSHIFT_MASTER_ITPAAS_PRIMARY}
OPENSHIFT_MASTER_PRIMARY_DEFAULT_PORT_HTTPS=${OPENSHIFT_MASTER_ITPAAS_PRIMARY_PORT_HTTPS}
OPENSHIFT_APPS_PRIMARY_DEFAULT=${OPENSHIFT_APPS_ITPAAS_PRIMARY}
OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT=${OPENSHIFT_PROXY_AUTH_ITPAAS_PRIMARY}
OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT="OPENSHIFT_USER_ITPAAS_MEPLEY"
OPENSHIFT_USER_PRIMARY_DEFAULT=${OPENSHIFT_USER_ITPAAS_MEPLEY[0]}
OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=${OPENSHIFT_USER_ITPAAS_MEPLEY[1]}
OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT=${OPENSHIFT_USER_ITPAAS_MEPLEY[2]}
OPENSHIFT_PROJECT_PRIMARY_DEFAULT=${OPENSHIFT_USER_ITPAAS_MEPLEY[3]}
: ${OPENSHIFT_APPLICATION_NAME_DEFAULT:=default-app}
: ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT:=json}

CONFIGURATION_DEMO_TARGET_ITPAAS_COMPLETED=true
