#!/bin/bash

HOST_LOCALHOST=`hostname`
HOST_LOCALHOST_SHORT=`hostname -s`
HOST_LOCALHOST_FQ=`hostname`

OPENSHIFT_DOMAIN_LOCAL=${HOST_LOCALHOST}

OPENSHIFT_DOMAIN=${OPENSHIFT_DOMAIN_LOCAL}


OPENSHIFT_MASTER_PRIMARY_PORT_HTTPS